Fix saucelabs errors after upgrades
The error:
WebDriverException: Message: Sauce-specific capabilities are no longer accepted as W3C WebDriver capabilities: avoidProxy, tags. Ensure to enclose these in sauce:options capabilities.